### PR TITLE
Robust: Check for more then one region at given coordinates

### PR DESCRIPTION
**Pull request by BruceStarfinder**
- Check for more then one region at given x, y coordinates
- Simplify MySQL region record lookup by x, y coordinates
- Cleanup commented out code to prevent potential bloating in built binary files
- Cleanup whitespaces
- Resharp files where necessary
- Add the curly brackets to the appropriate statements to ensure build and compile tools can exit statements in a clean way.

Signed-Off-By: BruceStarfinder<bruce@secondgalaxy.com>

### CODE REVIEW

**Review by emperorstarfinder — COMMENTED** [review]
This looks good to me but the one question that jumps out at me from a cursory review is:

Does this break the ability of locating regions for hypergrid teleport requests or does this have any impact on that?

**Comment by BruceStarfinder** [comment]
I haven't tested it as far as whether it breaks anything with hypergrid but it actually shouldn't because its just simply making the proper checks against any database that Virtual Universe runs on and not databases of grids not running Virtual Universe.

The only difference is that this simplifies the checks and makes sure the robust server can properly check for multiple regions at the same coordinates.

**Review by BritanyannStarfinder — APPROVED** [review]
This looks good to me.  In my local testing it does not appear to break anything related to Hypergrid.  Recommend merging.

**Review by emperorstarfinder — APPROVED** [review]
Upon further review and comments, I am in favor of this PR.

**Comment by emperorstarfinder** [comment]
Per discussion between Core Developers and Assistant Core Developers, I am closing this PR as Bruce will be including it in the new layout of the source code.

**Pull request closed without merging**
